feat: add MOMMY_REWARDS_ENABLED

diff --git a/src/main/sh/mommy b/src/main/sh/mommy
--- a/src/main/sh/mommy
+++ b/src/main/sh/mommy
@@ -68,6 +68,8 @@ did %%CAREGIVER%%'s %%SWEETIE%% make a big mess
 MOMMY_ENCOURAGEMENTS_EXTRA=""
 MOMMY_ENCOURAGEMENTS_ENABLED="1"
 
+MOMMY_REWARDS_ENABLED="1"
+
 MOMMY_FORBIDDEN_WORDS=""
 MOMMY_IGNORED_STATUSES="130"
 #endregion
@@ -405,13 +407,17 @@ test -f "$state_toggle_path"; state_toggle="$?"
 
 #region Parse Process state
 
-# Toggle Encouragements. If the second last ran command failed but on this command did not,
+# Toggle Rewards. If the second last ran command failed but on this command did not,
 # then we want to reward the user.
-#   0 = state file exists = the second last command was not a success.
-#   1 = the state file does not exist = the second last command a success.
+#   1 = state file exists = the second last command was not a success.
+#   0 = the state file does not exist = the second last command a success.
 state_process_path="$state_dir/pid_$PPID"
-test -f "$state_process_path"; state_failed_before="$?"
-
+! test -f "$state_process_path"; state_failed_before="$?"
+if [ "1" -eq "$MOMMY_REWARDS_ENABLED" ] && [ "1" -eq "$state_failed_before" ]; then
+    reward_user="1"
+else
+    reward_user="0"
+fi
 #endregion
 
 
@@ -477,7 +483,7 @@ else
     if list_any_equals "$command_exit_code" "$ignored_statuses"; then exit "$command_exit_code"; fi
 
     # Create or Delete stated_failed_before file if nessesary
-    if [ 0 -eq "$command_exit_code" ] && [ "0" -eq "$state_failed_before" ]; then
+    if [ 0 -eq "$command_exit_code" ] && [ "1" -eq "$state_failed_before" ]; then
         if ! rm -- "$state_process_path"; then die "mommy could not delete the process state file~"; fi
     elif [ 0 -ne "$command_exit_code" ]; then
         if ! mkdir -p -- "$state_dir"; then die "mommy could not create the state directory~"; fi
@@ -485,7 +491,7 @@ else
     fi
 
     # Populate list of templates
-    if [ 0 -eq "$command_exit_code" ] && ([ 1 -eq "$MOMMY_COMPLIMENTS_ENABLED" ] || [ "0" -eq "$state_failed_before" ]); then
+    if [ 0 -eq "$command_exit_code" ] && ([ 1 -eq "$MOMMY_COMPLIMENTS_ENABLED" ] || [ "1" -eq "$reward_user" ]); then
         templates="$MOMMY_COMPLIMENTS$n$MOMMY_COMPLIMENTS_EXTRA"
     elif [ 0 -ne "$command_exit_code" ] && [ 1 -eq "$MOMMY_ENCOURAGEMENTS_ENABLED" ]; then
         templates="$MOMMY_ENCOURAGEMENTS$n$MOMMY_ENCOURAGEMENTS_EXTRA"
