🗑️mommy now uses temporary storage and cleans up after herself~

diff --git a/src/main/sh/mommy b/src/main/sh/mommy
--- a/src/main/sh/mommy
+++ b/src/main/sh/mommy
@@ -411,7 +411,25 @@ test -f "$state_toggle_path"; state_toggle="$?"
 # then we want to reward the user.
 #   1 = state file exists = the second last command was not a success.
 #   0 = the state file does not exist = the second last command a success.
-state_process_path="$state_dir/pid_$PPID"
+if [ -n "$XDG_RUNTIME_DIR" ]; then
+    tmp_path="$XDG_RUNTIME_DIR/mommy/"
+elif [ -n "$TMPDIR" ]; then
+    tmp_path="$TMPDIR/mommy/"
+elif [ -d "/run/" ]; then
+    tmp_path="/run/mommy/"
+elif [ -d "/var/run" ]; then
+    tmp_path="/var/run/mommy/"
+elif [ -d "/tmp/" ]; then
+    tmp_path="/tmp/mommy/"
+else
+    die "mommy couldn't locate a suitable temporary directory~"
+fi
+
+if [ -d "$tmp_path" ]; then
+    find "$tmp_path" -type f -mtime +7 -exec rm -f {} \;
+fi
+
+state_process_path="$tmp_path/pid_$PPID"
 ! test -f "$state_process_path"; state_failed_before="$?"
 if [ "1" -eq "$MOMMY_REWARDS_ENABLED" ] && [ "1" -eq "$state_failed_before" ]; then
     reward_user="1"
@@ -452,7 +470,7 @@ if [ "x" != "x$opt_toggle" ]; then
         if ! rm -- "$state_toggle_path"; then die "mommy could not delete the state file~"; fi
         printf "mommy has been enabled for this user. mommy will once again display output. to disable mommy again, run 'mommy -t'~\n"
     else
-        if ! mkdir -p -- "$state_dir"; then die "mommy could not create the state directory~"; fi
+        if ! mkdir -p -- "$state_path"; then die "mommy could not create the state directory~"; fi
         if ! touch -- "$state_toggle_path"; then die "mommy could not create the state file~"; fi
         printf "mommy has been disabled for this user. mommy will not print any output until she is enabled again. to enable mommy again, run 'mommy -t'~\n"
     fi
@@ -486,7 +504,7 @@ else
     if [ 0 -eq "$command_exit_code" ] && [ "1" -eq "$state_failed_before" ]; then
         if ! rm -- "$state_process_path"; then die "mommy could not delete the process state file~"; fi
     elif [ 0 -ne "$command_exit_code" ]; then
-        if ! mkdir -p -- "$state_dir"; then die "mommy could not create the state directory~"; fi
+        if ! mkdir -p -- "$tmp_path"; then die "mommy could not create the state directory~"; fi
         if ! touch -- "$state_process_path"; then die "mommy could not create the process state file~"; fi
     fi
 
